version: "3.9"
services:
  # frontend:
  #   container_name: mdoj-frontend
  #   image: ghcr.io/mdcpp/mdoj/frontend:staging
  #   profiles: []
  #   depends_on:
  #     - backend
  #   ports:
  #     - "80:80"
  #   networks:
  #     - backend
  backend:
    container_name: mdoj-backend
    image: ghcr.io/mdcpp/mdoj/backend:staging
    profiles: [frontend-dev]
    depends_on:
      - judger
      - jaeger
    volumes:
      - ./backend/config:/config
      - ./backend/database:/database
    ports:
      - "8081:8081"
    networks:
      - judger
      - jaeger
  judger:
    container_name: mdoj-judger
    privileged: true
    image: ghcr.io/mdcpp/mdoj/judger:staging
    profiles: [backend-dev, frontend-dev]
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - judger
  jaeger:
    container_name: mdoj-jaeger
    image: jaegertracing/all-in-one
    profiles: [backend-dev, frontend-dev]
    ports:
      - "16686:16686"
    networks:
      - jaeger
networks:
  judger:
  backend:
  jaeger:
