version: "3.9"
services:
  # frontend:
  #   container_name: mdoj-frontend
  #   image: ghcr.io/mdcpp/mdoj/frontend:staging
  #   profiles: []
  #   depends_on:
  #     - backend
  #   ports:
  #     - "80:80"
  #   networks:
  #     - backend
  backend:
    container_name: mdoj-backend
    image: ghcr.io/mdcpp/mdoj/backend:staging
    profiles: [frontend-dev]
    depends_on:
      - judger
      - jaeger
    volumes:
      - ./backend/config:/config
      - ./backend/database:/database
    environment:
      - CONFIG_PATH=/config/config.toml
    ports:
      - "8081:8081"
    networks:
      - judger
      - jaeger
  judger:
    container_name: mdoj-judger
    privileged: true
    image: ghcr.io/mdcpp/mdoj/judger:staging
    profiles: [backend-dev, frontend-dev]
    volumes:
      - ./judger/config:/config
      - ./judger/plugins:/plugins
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /dev/fuse:/dev/fuse
    environment:
      - RUST_BACKTRACE=full
      - CONFIG_PATH=/config/config.toml
    ports:
      - "8082:8081"
    networks:
      - judger
  jaeger:
    container_name: mdoj-jaeger
    image: jaegertracing/all-in-one
    profiles: [backend-dev, frontend-dev]
    ports:
      - "16686:16686"
    networks:
      - jaeger
  migration:
    container_name: mdoj-migration
    image: ghcr.io/mdcpp/mdoj/migration:staging
    profiles: [migration]
    environment:
      - DATABASE_URL=sqlite://database/backend.sqlite?mode=rwc
    volumes:
      - ./backend/database:/database
networks:
  judger:
  backend:
  jaeger:
