version: "3.9"
services:
  frontend:
    container_name: mdoj-frontend
    image: ghcr.io/mdcpp/mdoj/frontend:staging
    profiles: [frontend-dev]
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - backend
  backend:
    container_name: mdoj-backend
    image: ghcr.io/mdcpp/mdoj/backend:staging
    profiles: [backend-dev, jaeger]
    depends_on:
      - judger
    ports:
      - "8081:8081"
    volumes:
      - ./database/:/database/
      - ./config/:/config/
    networks:
      - judger
      - jaeger
  judger:
    container_name: mdoj-judger
    privileged: true
    image: ghcr.io/mdcpp/mdoj/judger:staging
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - judger
  jaeger:
    container_name: mdoj-jaeger
    image: jaegertracing/all-in-one
    networks:
      - jaeger
networks:
  judger:
  backend:
  jaeger:
