address = "0.0.0.0:8080"
log = 1
# opentelemetry = "http://jaeger:4317"
default_role = "user"

[database]
path = "database/backend.sqlite"
salt = "be sure to change it"

[[judger]]
name = "http://judger:8080"
type = "static"

[grpc]
trust_host = ["192.168.216.0/24"]

[imgur]
client_id = "fffffffffffffff"
client_secret = "ffffffffffffffffffffffffffffffffffffffff"
