bind_address = "0.0.0.0:8081"
log_level = 2

[database]
path = "database/backend.sqlite"
salt = "be sure to change it"

[[judger]]
name = "http://mdoj-judger:8080"
type = "static"

[grpc]
trust_x_forwarded_for = true
public_pem = "../cert/cert.pem"
private_pem = "../cert/key.pem"

[imgur]
client_id = "fffffffffffffff"
client_secret = "ffffffffffffffffffffffffffffffffffffffff"
