log_level = 1

[runtime]
temp = "temp"
available_memory = 1073741824 # 1GiB
bind = "0.0.0.0:8080"

[nsjail]
runtime = "nsjail-sys/nsjail/nsjail"
# Require user namespace to run in rootless mode
# While it's possible to run without root, you still need access to cgroup 
rootless = false 
log = "/dev/null"

[plugin]
path = "plugins"
