version: "3.9"
services:
  frontend:
    container_name: mdoj-frontend
    image: ghcr.io/mdcpp/mdoj/frontend:staging
    depends_on:
      - backend
    ports:
      - "8080:8080"
    networks:
      - backend
  backend:
    container_name: mdoj-backend
    image: ghcr.io/mdcpp/mdoj/backend:staging
    depends_on:
      - judger
      - jaeger
    volumes:
      - ./backend.toml:/backend.toml
      - ./database:/database
    environment:
      - CONFIG_PATH=/backend.toml
    networks:
      - judger
      - jaeger
  judger:
    container_name: mdoj-judger
    privileged: true
    image: ghcr.io/mdcpp/mdoj/judger:staging
    cgroup: host
    devices:
      - /dev/fuse:/dev/fuse 
    volumes:
      - ./judger.toml:/judger.toml
      - ./plugins:/plugins
    environment:
      - RUST_BACKTRACE=full
      - CONFIG_PATH=/judger.toml
    networks:
      - judger
networks:
  judger:
  backend:
  jaeger:
