[frontend]
image_providers = ["https://i.imgur.com"]
api_server = "http://0.0.0.0:8081"

[[frontend.extension_language_mappings]]
extension = ["js"]
language = "javascript"

[[frontend.extension_language_mappings]]
extension = ["c"]
language = "c"

[[frontend.extension_language_mappings]]
extension = [
    "c++",
    "cpp",
    "cp",
    "cxx",
]
language = "javascript"

[[frontend.extension_language_mappings]]
extension = ["lua"]
language = "lua"

[backend]
trust_xff = false
