[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["migration"]

[dependencies]
moka = "0.11.1"
paste = "1.0.12"
prost = "0.11.9"

[dependencies.sea-orm]
version = "0.11.3"
features = ["sqlx-postgres", "runtime-actix-rustls", "macros", "mock", "sqlx-sqlite"]

[dependencies.tonic]
version = "0.9.2"
features = ["transport","channel","codegen","tls","prost"]

[build-dependencies]
tonic-build = "0.9.2"
