[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["migration"]

[dependencies]
env_logger = "0.10.0"
log = "0.4.18"
moka = "0.11.1"
paste = "1.0.12"
prost = "0.11.9"
toml = "0.7.4"
tokio-stream = "0.1.14"
once_cell = "1.17.2"

[dependencies.tokio]
version = "1.28.0"
features = ["rt-multi-thread", "process", "macros", "fs", "io-util"]

[dependencies.sea-orm]
version = "0.11.3"
features = [
    "sqlx-postgres",
    "runtime-actix-rustls",
    "macros",
    "mock",
    "sqlx-sqlite",
]

[dependencies.serde]
version = "1.0.163"
features = ["derive"]

[dependencies.tonic]
version = "0.9.2"
features = ["transport", "channel", "codegen", "tls", "prost"]

[build-dependencies]
tonic-build = "0.9.2"
