bind_address = "0.0.0.0:8081"
log_level = 0

[database]
path = "backend.sqlite"
salt = "be sure to change it"

[[judger]]
uri = "http://127.0.0.1:8080"

[grpc]
trust_x_forwarded_for = false
public_pem = "../cert.pem"
private_pem = "../key.pem"
