version: '3.9'
services:
  gateway: 
    container_name: mdoj-gateway
    build: ../frontend
    # remove comment if you need traefik
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.mdoj.rule=Host(`mdoj.example.com`)"
    #   - "traefik.http.services.mdoj.loadbalancer.server.port=80"
    #   - "traefik.http.middlewares.mdoj-grpcweb.grpcweb.allowOrigins=*"
    #   - "traefik.http.routers.mdoj.middlewares=mdoj-grpc"
    volumes:
      - ../frontend/build:/usr/share/nginx/html
    ports:
      - "80:80"
    networks:
      - backend
  backend:
    container_name: mdoj-backend
    build: ../backend
    volumes:
      - ./database/:/database/
      - ./config/:/config/
    networks:
      - backend
      - judger
  judger:
    container_name: mdoj-judger
    # you can actually turn this off if you setup the cgroup properly(user of the container should own the cgroup)
    privileged: true
    build: ../judger
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - ./config/:/config/
    networks:
      - judger
networks:
  judger:
  backend:
