version: '3'
services:
  web:
    build: .
    environment:
      - POSTGRES=postgres://postgres:postgres@postgres/postgres
      - HOST=0.0.0.0
      - PORT=8080
    volumes:
      - logvolume:/log
    # debug
    ports:
      - "8079:8080"
    links:
      - postgres
  postgres:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./route/src/entity/init:/docker-entrypoint-initdb.d:ro
      - database-data:/var/lib/postgresql/data
  nginx:
    build: ./nginx/
    environment:
      - DOMAIN=hackathon.easonabc.eu.org
      # volumes:
      # - ./nginx/conf.d:/etc/nginx/conf.d:ro
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./conf.d:/etc/nginx/conf.d/default.conf
      # - pem:/etc/nginx/cert/star_xx_com.pem
      # - key:/etc/nginx/cert/star_xx_com.key
      # - crt:/etc/nginx/cert/star_xx_com.crt
    ports:
      - 8080:8080
      # - 443:443
    links:
      - web
volumes:
  logvolume: {}
  database-data: {}
