bind_address = "0.0.0.0:8081"
log_level = 0
opentelemetry = true

[database]
path = "database/backend.sqlite"
salt = "be sure to change it"

[[judger]]
name = "http://127.0.0.1:8080"
type = "static"

[grpc]
trust_x_forwarded_for = false
public_pem = "../cert/cert.pem"
private_pem = "../cert/key.pem"
