bind_address = "0.0.0.0:8081"
log_level = 2
opentelemetry = true

[database]
path = "database/backend.sqlite"
salt = "be sure to change it"

[[judger]]
name = "mdoj-judger"
type = "swarm"

[grpc]
trust_x_forwarded_for = true
public_pem = "../cert/cert.pem"
private_pem = "../cert/key.pem"
