name: Publish staging build for frontend

on:
  push:
    branches:
      - "staging"
    paths:
      - "frontend/**"
      - .github/workflows/frontend.yml

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Checkout submodule
        run: git submodule update --init --recursive
      - name: Install Just
        uses: taiki-e/install-action@just
      - name: Install docker
        uses: docker-practice/actions-setup-docker@master
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build frontend
        uses: docker/build-push-action@v5
        with:
          build-args: ARCH=x86_64
          context: .
          file: "./frontend/Dockerfile"
          push: true
          tags: "ghcr.io/mdcpp/mdoj/frontend:staging"
          labels: "frontend"
          cache-from: type=gha
          cache-to: type=gha,mode=max
