name: judger ci

on:
  push:
    branches:    
      - '*'   
    paths:
      - judger/**

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install ProtoBuffer compiler
        run: sudo apt install -y protobuf-compiler
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path ./judger/Cargo.toml
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path ./judger/Cargo.toml
